### ISSUE TITLE
Roadmap to v0.4

### ISSUE THREAD

**Issue by valkyrienyanko** [The-MMORPG-Project/Game-Server#37]
Note that __this__ roadmap is a mess and will be spread out in the future.

## Web / Game Server
* [ ] Only one client may be logged into one account at a time.
* [ ] Show account names hovering above all clients.
* [ ] Server / Client only send position updates when they are in a specified range of other clients.
* [ ] Banned IPs and / or Accounts should be blocked from connecting to the game and / or server connection in general.
* [x] Fix all console buffer related issues.
* [ ] Figure out how to properly setup System.Threads.
* [ ] Add server and client packets for chat
* [ ] Global chat
* [ ] Global currency
* [ ] Friend management

## Unity Client
* [ ] Permissions and commands to mute, kick and ban users
* [ ] Add in-game chat UI

## Other
* [ ] Curse Filtering in account usernames and all chat related modules
